### ISSUE TITLE
PredicateEditor in Objective C

### ISSUE THREAD

**Issue by AsKaeternam** [arvindhsukumar/PredicateEditor#1]
Hello dear,

First of all, thank you for your awesome project, that's really easily to create and manage forms and predicate.

Unfortunately, i would like to use your project in an Objective C project.

The problem come from the struct "KeyPathDescriptor" that I'm not able to use in my Objective C class.

Do you have a workaround or will you create an Objective C alternative ?

Thank you in advance for your answer,

Best regards

**Comment by arvindhsukumar** [comment]
Thanks @AsKaeternam.

I'll work on this.  I do understand Obj C compatibility is essential from an iOS development point of view. It just wasn't a priority for the initial release.

I'll also update the Readme to reflect this.
